LAB_DESCRIPTION="SYN Flood Lab: PC1 Attacker, PC2 Tester, PC3 Server, R1 Router"
LAB_VERSION=2.0
LAB_AUTHOR="TheRedCowboy"

# --- Network A ---
pc1[0]="A"
pc1[image]="kathara/base"
pc1[ipv6]="false"

pc2[0]="A"
pc2[image]="kathara/base"
pc2[ipv6]="false"

# --- ROUTER ---
r1[0]="A"
r1[1]="B"
r1[image]="kathara/base"
r1[ipv6]="false"

# --- Network B ---
pc3[0]="B"
pc3[image]="kathara/base"
pc3[ipv6]="false"

pc3[privilege] = "true"
